<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="s" uri="/struts-tags"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
	table{
		margin: 20px auto;
		border: 1pt solid black;
		border-collapse: collapse;
		width: 100%;
	}
	td{
		border: 1pt solid black;
	}
</style>
<title>PDFDemno</title>
</head>
<body>
	<table cellspacing="0" align="center">
		<caption>Demo标题</caption>
		<tr>
			<th>学号</th>
			<th>姓名</th>
			<th>性别</th>
			<th>班级</th>
		</tr>
		<tr>
			<td><img src="http://img0.bdstatic.com/img/image/shouye/qddamx03.jpg" /></td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>1</td>
			<td>李梅</td>
			<td>女</td>
			<td>计算机1203</td>
		</tr>
		<tr>
			<td>2</td>
			<td>李建</td>
			<td>男</td>
			<td>计算机1203</td>
		</tr>
	</table>
</body>
</html>